version: '3'
services:
  tinfoil-hat:
    labels:
      # same scop used by watchtower to self update image
      - "com.centurylinklabs.watchtower.scope=tinfoilhat"
    container_name: tinfoil-hat
    build: .
    image: vinicioslc/tinfoil-hat:latest
    hostname: tinfoil-hat
    environment:
      - DEBUG=*
      # users list authorized to access tinfoil-hat
      # user and password separated by ":" and users separated by ","
      # <your-user>:<your-pass>,<another-user>:<another-pass> (this blocks browser access too)
      # - AUTH_USERS=admin:123
      - UNAUTHORIZED_MSG='No tricks and treats for you!!'
      - WELCOME_MSG='The Server Just Works!!'
    ports:
      # Change to any port of your machine (99 in that case) (dont change the :80 !!!)
      - 99:80
      # you can now access on your browser http://localhost:99 and see your games
    volumes:
      # path to your custom shop_template.jsonc used to show message on success or add authentication
      - ./shop_template.jsonc:/shop_template.jsonc
      # path to your directory with games
      - c:/Users/vinic/Downloads/FDM/Switch/:/games/
  # to enable auto update of tinfoil-hat container
  tinfoilhat-updater:
    image: containrrr/watchtower:latest
    volumes:
      # get
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      # put your timezone here
      - WATCHTOWER_POLL_INTERVAL=120
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_SCOPE=tinfoilhat
    labels:
      com.centurylinklabs.watchtower.enable: false
