version: '3'
services:
  app:
    container_name: tinfoil-hat
    build: .
    image: tinfoil-hat:latest
    hostname: tinfoil-hat
    environment:
      - DEBUG=*
    ports:
      # Change to any port of your machine (7878 in that case) (dont change the :80 !!!)
      - 7878:80
      # you can now access on your browser http://localhost:7878 and see your games
    volumes:
      # path to your custom shop_template.jsonc used to show message on success or add authentication
      - ./shop_template.jsonc:/shop_template.jsonc
      # path to your directory with games
      - c:/Users/vinic/Downloads/FDM/Switch/:/games/
